export const COLORPICKER = "colorPicker";
export const RANGESLIDER = "rangeSlider";
export const CHECKBOX = "checkbox";
export const GRADIENTPICKER = "gradientPicker";

/* export const baseProperty = [
  {
    propertyName: "Border Radius",
    type: RANGESLIDER,
    min: "-150",
    max: "150",
    value: "0",
    step: "2",
    active: false,
  },
  {
    propertyName: "Box Color",
    type: COLORPICKER,
    value: "#ff0080",
    active: false,
  },
  {
    propertyName: "Text Color",
    type: COLORPICKER,
    value: "#0f0f0f",
    active: false,
  },
];

export const boxShadowProperty = [
  {
    propertyName: "Horizontal Length",
    type: RANGESLIDER,
    min: "-200",
    max: "200",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Vertical Length",
    type: RANGESLIDER,
    min: "-200",
    max: "200",
    value: "0",
    step: "1",
    active: false,
  },

  {
    propertyName: "Blur Radius",
    type: RANGESLIDER,
    min: "0",
    max: "300",
    value: "50",
    step: "1",
    active: false,
  },
  {
    propertyName: "Spread Radius",
    type: RANGESLIDER,
    min: "-200",
    max: "200",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Shadow Color",
    type: COLORPICKER,
    value: "#aabbcc",
    active: false,
  },
  {
    propertyName: "Shadow Opacity",
    type: RANGESLIDER,
    min: "0",
    max: "1",
    value: "1",
    step: "0.05",
    active: false,
  },
  { propertyName: "Outline", type: CHECKBOX, status: false, active: false },
];

export const backgroundGradientProperty = [
  {
    propertyName: "Background Gradient",
    type: GRADIENTPICKER,
    orientation: "linear-gradient",
    degree: {
      min: "0",
      max: "360",
      value: "0",
      step: "1",
      propertyName: "Degree",
    },
    firstColor: {
      hex: "#BF3E3E",
      hsl: {
        a: 0.5,
        h: 0,
        l: 51,
        s: 50,
      },
      rgb: {
        a: 0.5,
        b: 191,
        g: 62,
        r: 62,
      },
    },

    secondColor: {
      hex: "#867272",
      hsl: {
        a: 0.5,
        h: 0,
        l: 51,
        s: 50,
      },
      rgb: {
        a: 0.5,
        b: 0,
        g: 8,
        r: 49,
      },
    },
    active: false,
  },
];

export const textShadowProperty = [
  {
    propertyName: "Shift Right",
    type: RANGESLIDER,
    min: "-40",
    max: "40",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Shift Down",
    type: RANGESLIDER,
    min: "-40",
    max: "40",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Blur",
    type: RANGESLIDER,
    min: "0",
    max: "20",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Text Shadow Opacity",
    type: RANGESLIDER,
    min: "0",
    max: "1",
    value: "1",
    step: "0.05",
    active: false,
  },
  {
    propertyName: "Text Shadow Color",
    type: COLORPICKER,
    value: "#69C2A1",
    active: false,
  },
  {
    propertyName: "Scale",
    type: RANGESLIDER,
    min: "0",
    max: "2",
    value: "1",
    step: "0.1",
    active: false,
  },
  {
    propertyName: "Rotate",
    type: RANGESLIDER,
    min: "0",
    max: "360",
    value: "0",
    step: "1",
    active: false,
  },
];

export const transformProperty = [
  {
    propertyName: "Translate X",
    type: RANGESLIDER,
    min: "-50",
    max: "50",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Translate Y",
    type: RANGESLIDER,
    min: "-50",
    max: "50",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Skew X",
    type: RANGESLIDER,
    min: "-90",
    max: "90",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Skew Y",
    type: RANGESLIDER,
    min: "-90",
    max: "90",
    value: "0",
    step: "1",
    active: false,
  },
];
 */
export const cssProperty = [
  /* ---------------------Base Property(0-2)-------------------- */
  {
    propertyName: "Border Radius",
    type: RANGESLIDER,
    min: "0",
    max: "150",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Box Color",
    type: COLORPICKER,
    value: "#ff0080",
    active: false,
  },
  {
    propertyName: "Text Color",
    type: COLORPICKER,
    value: "#0f0f0f",
    active: false,
  },
  /* ---------------------Box Shadow Property(3-9)-------------------- */
  {
    propertyName: "Horizontal Length",
    type: RANGESLIDER,
    min: "-200",
    max: "200",
    value: "10",
    step: "1",
    active: false,
  },
  {
    propertyName: "Vertical Length",
    type: RANGESLIDER,
    min: "-200",
    max: "200",
    value: "10",
    step: "1",
    active: false,
  },

  {
    propertyName: "Blur Radius",
    type: RANGESLIDER,
    min: "0",
    max: "300",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Spread Radius",
    type: RANGESLIDER,
    min: "-200",
    max: "200",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Shadow Color",
    type: COLORPICKER,
    value: "#0c140e",
    active: false,
  },
  {
    propertyName: "Shadow Opacity",
    type: RANGESLIDER,
    min: "0",
    max: "1",
    value: "1",
    step: "0.05",
    active: false,
  },
  { propertyName: "Outline", type: CHECKBOX, status: false, active: false },
  /* ---------------------Background Gradient Property(10)-------------------- */
  {
    propertyName: "Background Gradient",
    type: GRADIENTPICKER,
    orientation: "linear-gradient",
    degree: {
      min: "0",
      max: "360",
      value: "0",
      step: "1",
      propertyName: "Degree",
    },
    position: {
      min: "0",
      max: "100",
      value: "50",
      step: "1",
      propertyName: "Position",
    },
    firstColor: {
      hex: "#BF3E3E",
      hsl: {
        a: 0.5,
        h: 0,
        l: 51,
        s: 50,
      },
      rgb: {
        a: 0.5,
        b: 191,
        g: 62,
        r: 62,
      },
    },

    secondColor: {
      hex: "#867272",
      hsl: {
        a: 0.5,
        h: 0,
        l: 51,
        s: 50,
      },
      rgb: {
        a: 0.5,
        b: 0,
        g: 8,
        r: 49,
      },
    },
    active: false,
  },
  /* ---------------------Text Shadow Property(11-15)-------------------- */
  {
    propertyName: "Shadow LengthX",
    type: RANGESLIDER,
    min: "-40",
    max: "40",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Shadow LengthY",
    type: RANGESLIDER,
    min: "-40",
    max: "40",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Blur",
    type: RANGESLIDER,
    min: "0",
    max: "20",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Text Shadow Opacity",
    type: RANGESLIDER,
    min: "0",
    max: "1",
    value: "1",
    step: "0.05",
    active: false,
  },
  {
    propertyName: "Text Shadow Color",
    type: COLORPICKER,
    value: "#69C2A1",
    active: false,
  },
  /* ---------------------Transform Property(16-21)-------------------- */
  {
    propertyName: "Scale",
    type: RANGESLIDER,
    min: "0",
    max: "2",
    value: "1",
    step: "0.1",
    active: false,
  },
  {
    propertyName: "Rotate",
    type: RANGESLIDER,
    min: "0",
    max: "360",
    value: "0",
    step: "1",
    active: false,
  },

  {
    propertyName: "Translate X",
    type: RANGESLIDER,
    min: "-50",
    max: "50",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Translate Y",
    type: RANGESLIDER,
    min: "-50",
    max: "50",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Skew X",
    type: RANGESLIDER,
    min: "-90",
    max: "90",
    value: "0",
    step: "1",
    active: false,
  },
  {
    propertyName: "Skew Y",
    type: RANGESLIDER,
    min: "-90",
    max: "90",
    value: "0",
    step: "1",
    active: false,
  },
];
